<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Analiza sentymentu</title>

<script src="site_libs/header-attrs-2.21/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Analiza książek Juliusza Verne'a</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">O analizie</a>
</li>
<li>
  <a href="preprocessing.html">Przygotowanie</a>
</li>
<li>
  <a href="chmury.html">Chmury</a>
</li>
<li>
  <a href="macierze_wystapien.html">Macierze wystąpień</a>
</li>
<li>
  <a href="sentyment.html">Analiza sentymentu</a>
</li>
<li>
  <a href="watek.html">Analiza wątku</a>
</li>
<li>
  <a href="grupowanie.html">Grupowanie</a>
</li>
<li>
  <a href="klasyfikacja.html">Klasyfikacja</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Analiza sentymentu</h1>

</div>


<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
<div id="słownik-bing---zero-jedynkowy-wskaźnik-nastroju"
class="section level2">
<h2>Słownik BING - zero jedynkowy wskaźnik nastroju</h2>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
<p><u><strong>Słownik Bing</strong></u> to zbiór słów kluczowych z
przypisanymi wartościami sentymentalnymi:</p>
<ul>
<li><p>pozytywnymi,</p></li>
<li><p>negatywnymi,</p></li>
<li><p>neutralnymi.</p></li>
</ul>
<p>W analizie sentymentu według słownika Bing, tekst jest przetwarzany
pod kątem występowania tych słów, co pozwala na określenie ogólnego
nastroju lub emocji wyrażanych w tekście. Dzięki temu narzędziu można
ocenić, czy tekst ma pozytywny, negatywny czy neutralny charakter.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>bing_sentiments <span class="ot">&lt;-</span> <span class="fu">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>eighty_days_sentiments_bing <span class="ot">=</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(eighty_days_tokens, bing_sentiments, <span class="at">by =</span> <span class="st">&quot;word&quot;</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>all_moon_sentiments_bing <span class="ot">=</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(all_moon_tokens, bing_sentiments, <span class="at">by =</span> <span class="st">&quot;word&quot;</span>)</span></code></pre></div>
<ul>
<li><strong>“W 80 dnii dookoła świata”</strong></li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>eighty_days_bing <span class="ot">&lt;-</span> eighty_days_tokens <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(bing_sentiments, <span class="at">by =</span> <span class="st">&quot;word&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(chapter, sentiment) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(sentiment, n, <span class="at">fill =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sentiment =</span> positive <span class="sc">-</span> negative)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(eighty_days_bing, <span class="fu">aes</span>(<span class="at">x =</span> chapter, <span class="at">y =</span> sentiment)) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>, <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Wskaźnik nastroju w &#39;W 80 dni dookoła świata&#39; J. Verne wg leksykonu Bing&quot;</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Rozdział&quot;</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sentyment&quot;</span>)</span></code></pre></div>
<p><img src="sentyment_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Z wskaźnik nastroju (pozytywne-negatywne emocje) w książce ‘W 80 dni
dookoła świata’ można wyciągnąć kilka wniosków:</p>
<ul>
<li><p>w początkowych rozdziałach (1-10) dominuje pozytywny sentyment,
co sugeruje początkową beztroskę i optymizm w narracji.</p></li>
<li><p>następnie, w rozdziałach 11-15, pojawia się wyraźny spadek
nastroju, gdzie negatywny sentyment staje się bardziej widoczny, jednka
w rozdziale 14 mamy nagly wzrost nastroju, największy dla całej książki.
To może wskazywać na rozwijającą się intrygę lub pojawienie się
trudności dla bohaterów,</p></li>
<li><p>w kolejnych rozdziałach (16-20) obserwuje się pewne zrównoważenie
między pozytywnym a negatywnym sentymentem, co sugeruje pewien stabilny
przebieg wydarzeń,</p></li>
<li><p>jednak w późniejszych rozdziałach (21-37) znowu pojawia się
częsty spadek nastroju, gdzie negatywny sentyment przeważa. To może
oznaczać kluczowe momenty konfliktu lub trudności, które bohaterowie
muszą pokonać,</p></li>
<li><p>książka kończy się pozytywnym nastrojem, lecz niezbyt
wysokim.</p></li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(eighty_days_bing, <span class="fu">aes</span>(<span class="at">x =</span> chapter)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> positive, <span class="at">fill =</span> <span class="st">&quot;Positive&quot;</span>), <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> negative, <span class="at">fill =</span> <span class="st">&quot;Negative&quot;</span>), <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Sentyment w &#39;W 80 dni dookoła świata&#39; J. Verne wg leksykonu Bing&quot;</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Rozdział&quot;</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sentyment&quot;</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Sentyment&quot;</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Positive&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightseagreen&quot;</span>, <span class="st">&quot;Negative&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>)) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">&quot;Sentyment&quot;</span>))</span></code></pre></div>
<p><img src="sentyment_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>W celu głębszej analizy przedstawiono również wykres, na którym można
porównać ilość pozytywnych i negatywnych emocji. Na jego podstawie
wyciągnięto dodatkowe wnisoki:</p>
<ul>
<li><p>można powiedzieć że w książce “w 80 dnii dookoła świata”
przeważają pozytywne emocje,</p></li>
<li><p>ilość negaywtnych emocji przeważa na przełomie 1/3 książki
(rozdziały 11-13) oraz w pojedyńczych rozdziałach w drugiej połowie -
rozdziały 21, 28, 30 i 34,</p></li>
<li><p>Najbardziej emocjonalne rozdziały, w których jednocześnie ciężko
jednoznacznie roztrzygnąć o emocjach również znajdują się w drugiej
połowie książki, są to 21 oraz 33,</p></li>
<li><p>przewagę pozytywnych emocjii nad negatywynymi można jednoznczanie
zauważyć na początku ksiązki, na jej końcu obserwuje się zauważalny
spadek pozytywności.</p></li>
</ul>
<p>Analiza sentymentu według słownika Bing w książce “W 80 dni dookoła
świata” pozwala zauważyć, że nastroje w narracji są zróżnicowane. Na
początku dominuje pozytywny sentyment, co odzwierciedla beztroską
atmosferę i optymizm. Jednak w środkowych rozdziałach występuje wyraźny
spadek nastroju, zaznaczający się większą ilością negatywnych emocji. W
pewnym momencie następuje jednak nagły wzrost nastroju, najwyższy w
całej książce. W drugiej połowie książki negatywny sentyment jest
zauważalny ale neutralizowany przez pozytwyny, co może wskazywać na
kluczowe momenty konfliktu i trudności. Mimo to, książka kończy się z
umiarkowanie pozytywnym nastrojem. Ogólnie rzecz biorąc, analiza danych
sentymentalnych wskazuje na dynamiczną naturę fabuły, z różnymi
emocjonalnymi momentami.</p>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
<ul>
<li><strong>“Wokół księżyca”</strong></li>
</ul>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>all_moons_bing <span class="ot">&lt;-</span> all_moon_tokens <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(bing_sentiments, <span class="at">by =</span> <span class="st">&quot;word&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(chapter, sentiment) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(sentiment, n, <span class="at">fill =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sentiment =</span> positive <span class="sc">-</span> negative)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(all_moons_bing, <span class="fu">aes</span>(<span class="at">x =</span> chapter, <span class="at">y =</span> sentiment)) <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>, <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Wskaźnik nastroju w &#39;Wokół księżyca&#39; J. Verne wg leksykonu Bing&quot;</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Rozdział&quot;</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sentyment&quot;</span>)</span></code></pre></div>
<p><img src="sentyment_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Na podstawie wykresu przedstawiającego wskaźnik nastroju w powieści
‘Wokół księżyca’ można powiedzieć:</p>
<ul>
<li>pozytywny sentyment definitywnie towarzyszy czytelnikowi całą
książke,</li>
<li>rozdziały 15 i 16 mają negatywny sentyment, co stanowi kontrast w
stosunku do innych rozdziałów. To może wskazywać na momenty konfliktu
lub trudności, które dodają napięcia i zmieniają ton narracji,</li>
<li>istnieje kilka rozdziałów (10 i 22), gdzie sentyment jest relatywnie
niski,</li>
<li>ostatnie rozdziały prezentują coraz to weselszą atmosferę. Końcowy
rozdział charakteryzuje się największym wynikiem wskaźnika, co sugeruje
zdecydowany happy end.</li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(all_moons_bing, <span class="fu">aes</span>(<span class="at">x =</span> chapter)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> positive, <span class="at">fill =</span> <span class="st">&quot;Positive&quot;</span>), <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> negative, <span class="at">fill =</span> <span class="st">&quot;Negative&quot;</span>), <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Sentyment w &#39;Wokół księżyca&#39; J. Verne wg leksykonu Bing&quot;</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Rozdział&quot;</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sentyment&quot;</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Sentyment&quot;</span>) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Positive&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightseagreen&quot;</span>, <span class="st">&quot;Negative&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>)) <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">&quot;Sentyment&quot;</span>))</span></code></pre></div>
<p><img src="sentyment_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>W celu głębszej analizy przedstawiono również wykres, na którym
pozytywne i negatywne sentymenty są rozdzielone. Na jego podstawie
wyciągnięto dodatkowe wnioski:</p>
<ul>
<li><p>rozdział 3 ma najwyższy pozytywny i negatywny sentyment, co
sugeruje obecność zarówno negatywnych, jak i pozytywnych wydarzeń lub
emocji w tym rozdziale. Może to wskazywać na złożoność fabuły lub
konflikty,</p></li>
<li><p>ogólny wysoki pozytywny sentyment w rozdziale 3 zauważony na
poprzednim wykresie składa się z bardzo wysokiego zarówno pozytywnego
jak i negatywnego sentymentu. Może to wskazywać na złożoność fabuły i
emocjonalny czas.</p></li>
<li><p>podobnie rozdziały 15 i 16 charakteryzują się jednocześnie
wysokim wskaźnikiem pozytywności jak i negatywności, z przewagą tego
drugiego, stąd sumarycznie negatywny wydźwięk zauważony na poprzednim
wykresie. Tu również czytelnik może odczuć emocjonalny czas dla
bohaterów,</p></li>
<li><p>na początku i na końcu książki obserwuje się niski wskaźnik
negatywnego sentymentu (abstrahując od pozytywnego), a wraz z fabuła
ogólnie rośnie wskaźnik pozytynego sentymentu.</p></li>
<li><p>najwyższy pozytywny sentyment (abstrahując od negatywnego)
występuje w rozdziale 3 i dwóch ostatnich: 24 i 25.</p></li>
</ul>
<p>Na podstawie analizy sentymentu według słownika Bing w książce “Wokół
księżyca” można powiedzieć, że cała książka jest generalnie nacechowana
pozytywnym sentymentem, co sugeruje, że optymizm i dobre emocje
towarzyszą czytelnikowi przez całą fabułę. Rozdziały 15 i 16 wyróżniają
się negatywnym sentymentem, stanowiąc kontrast w stosunku do reszty
rozdziałów. Może to wskazywać na wystąpienie momentów konfliktu lub
trudności, które dodają napięcia i zmieniają ton narracji. Ponadto
wspomniane rozdziały wraz z 3 cechują się wysokim poziomem zarówno
pozytywnego, jak i negatywnego sentymentu, co może wskazywać na
intensywne emocje i dynamikę. Ostatni rozdział osiąga najwyższy wynik
wskaźnika sentymentu, co sugeruje zdecydowany happy end.</p>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
<ul>
<li><strong>Podsumowanie</strong></li>
</ul>
<p>Porównując dwie analizy sentymentu w książkach “W 80 dni dookoła
świata” i “Wokół księżyca”, można zauważyć pewne podobieństwa i różnice.
W obu przypadkach analiza sentymentu wykazuje zróżnicowane nastroje w
narracji, jednak w przypadku “Wokół księżyca” jest to dużo mniejsza
dynamika niż w “W 80 dni dookoła świata”. Obie książki rzopocznają się
pozytywnie i kończą happy endem. Sugerując czytelnikom, można
powiedzieć, że “W 80 dni dookoła świata” oferuje dynamiczną fabułę z
różnymi emocjonalnymi momentami, podczas gdy “Wokół księżyca” zapewnia
optymizm i dobre emocje przez większość historii. Oba tytuły mogą być
interesujące dla osób poszukujących różnorodności nastrojów i emocji w
literaturze.</p>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
</div>
<div id="słownik-affin---ważony-wskaźnik-nastroju"
class="section level2">
<h2>Słownik AFFIN - ważony wskaźnik nastroju</h2>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
<p><u><strong>Słownik AFINN</strong></u> (Affinity Lexicon) to słownik,
który przypisuje wartości sentymentalne słowom w tekście. Słowa są
oceniane liczbowo na skali od -5 do +5, gdzie wartości ujemne oznaczają
negatywny sentyment, a wartości dodatnie oznaczają pozytywny
sentyment.</p>
<p>Słownik AFINN zawiera mniejw wyrazów niż Bing, skupia się na słowach
mających wyraźny wydźwięk sentymentalny, a jego głównym celem jest
identyfikowanie i mierzenie emocjonalnej zawartości tekstu. Je</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>afinn_sentiments <span class="ot">&lt;-</span> <span class="fu">get_sentiments</span>(<span class="st">&quot;afinn&quot;</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>eighty_days_sentiments_afinn <span class="ot">=</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(eighty_days_tokens, afinn_sentiments, <span class="at">by =</span> <span class="st">&quot;word&quot;</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>all_moon_sentiments_affin <span class="ot">=</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(all_moon_tokens, afinn_sentiments, <span class="at">by =</span> <span class="st">&quot;word&quot;</span>)</span></code></pre></div>
<p>Jako że rezultat zastosowania słownika Affin jest bardzo podobny do
wykresów wykonanych za pomocą słownika Bing, poniższa analiza jest w
formie porównawczej aby nie powielać wniosków.</p>
<ul>
<li><strong>“W 80 dnii dookoła świata”</strong></li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>eighty_days_afinn <span class="ot">&lt;-</span> eighty_days_sentiments_afinn <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(chapter) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">value =</span> <span class="fu">sum</span>(value))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>eighty_days_bing_comparison <span class="ot">&lt;-</span> eighty_days_bing <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">value =</span> sentiment)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>combined_sentiments <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(eighty_days_afinn, <span class="at">lexicon =</span> <span class="st">&quot;Afinn&quot;</span>),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(eighty_days_bing_comparison[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>)], <span class="at">lexicon =</span> <span class="st">&quot;Bing&quot;</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined_sentiments, <span class="fu">aes</span>(<span class="at">x =</span> chapter, <span class="at">y =</span> value, <span class="at">fill =</span> lexicon)) <span class="sc">+</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Porównanie sentymentu w powieściach&quot;</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Rozdział&quot;</span>,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sentyment&quot;</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Leksykon&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Afinn&quot;</span> <span class="ot">=</span> <span class="st">&quot;steelblue&quot;</span>, <span class="st">&quot;Bing&quot;</span> <span class="ot">=</span> <span class="st">&quot;peachpuff&quot;</span>)) <span class="sc">+</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="sentyment_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Porównując sentyment według dwóch słowników, Affin i Bing, w książce
“80 dni dookoła świata”, można zauważyć pewne różnice w interpretacji
nastroju:</p>
<ul>
<li><p>pierwsze rozdziały są bardziej pozytywne w przypadku Affin, z
odwróceniem sentymentu w rozdziale 5. Może sugerować to trudności na
drodze bohaterów, nie wykryte przez słownik Bing,</p></li>
<li><p>środek książki (rozdziały 17-27) jest znacząco bardziej pozytywny
niż sugerował to Bing,</p></li>
<li><p>na końcu książki za pomocą słownika Affin w odróżnieniu do Bing
można zauważyć przewagę negatywności (rozdziały 32-36) z happy endem
(pozytywność na poziomie początku książki),</p></li>
<li><p>wiele sentymentów zostało odwróconych według Affin, sugerując
inną dynamikę</p>
<ul>
<li><p>do negatywnych rozdziałów należą: 5 (Bing: pozytywny), 8 (Bing:
neutralny),16 (Bing: pozytywny), 32-33, 35 (Bing: pozytywny),</p></li>
<li><p>a do pozytywnych: 18 (Bing: negaytwyny), 21 (Bing:
neutralny)</p></li>
</ul></li>
<li><p>według obu słowników najbardziej pozytywnym rozdziałem jest 14.
Podobnie w przypadku negatywnego, oba słowniki są zgodne co do rozdziału
30, jednakże affin sugeruje, że podobnie negatywny wydźwięk ma rozdział
15. To może być najbardziej emocjonalny moment książki, gdyż po dużym
pozytywiźmie następuje duży negatywizm. Bohaterzy mogli przykładowo
doświadzczyć tutaj straty.</p></li>
</ul>
<p>Słownik Affin wydaje się bardziej skłonny do wykrywania pozytywnych
sentymentów niż Bing w książce “80 dni dookoła świata”. Ogólnie rzecz
biorąc, sentymenty według Affin są wyższe niż według Bing. Istnieją
również różnice interpretacji nastroju w poszczególnych rozdziałach,
gdzie Affin często odwraca sentymenty w porównaniu do Bing.</p>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
<ul>
<li><strong>“Wokół księżyca”</strong></li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>all_moon_afinn <span class="ot">&lt;-</span> all_moon_sentiments_affin <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(chapter) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">value =</span> <span class="fu">sum</span>(value))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>all_moon_bing_comparison <span class="ot">&lt;-</span> all_moons_bing <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">value =</span> sentiment)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>combined_sentiments <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(all_moon_afinn, <span class="at">lexicon =</span> <span class="st">&quot;Afinn&quot;</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(all_moon_bing_comparison[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>)], <span class="at">lexicon =</span> <span class="st">&quot;Bing&quot;</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined_sentiments, <span class="fu">aes</span>(<span class="at">x =</span> chapter, <span class="at">y =</span> value, <span class="at">fill =</span> lexicon)) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Porównanie sentymentu w powieściach&quot;</span>,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Rozdział&quot;</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sentyment&quot;</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Leksykon&quot;</span>) <span class="sc">+</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Afinn&quot;</span> <span class="ot">=</span> <span class="st">&quot;steelblue&quot;</span>, <span class="st">&quot;Bing&quot;</span> <span class="ot">=</span> <span class="st">&quot;peachpuff&quot;</span>)) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="sentyment_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Porównując sentyment według dwóch słowników, Affin i Bing, w książce
“Wokół księżyca”, można wyciągnąc wnioski:</p>
<ul>
<li><p>słownik Affin wykrywa wyższe sentymenty niż Bing w trakcie całej
książki, poza rozdziałami 2 i 5,</p></li>
<li><p>według Affin żaden rozdział nie jest zaklafikowany jako
negatywny, Bing wymienił 15 i 16,</p></li>
<li><p>ponadto rozdziałami o najniższym sentymencie są teraz 2 i 5, co
może sugerować mniejszy optymizm na początku przygody lub większe
problemy. Ogólnie rzecz biorąc początek książki według Affin jest
bardziej dynamiczny jeżeli chodzi o sentyment niż według Bing,</p></li>
<li><p>koniec książki bardziej wyróżnia się pozytywnym zakończeniem
aniżeli w przypadku słownika Bing.</p></li>
</ul>
<p>Podsumowując, analiza sentymentu za pomocą słowników Affin i Bing w
książce “Wokół księżyca” ukazuje różnice w interpretacji nastroju, ze
szczególnym uwzględnieniem pozytywnych aspektów. Słownik Affin wykazuje
tendencję do wykrywania większej liczby pozytywnych sentymentów niż
Bing, co wpływa na ogólny odbiór emocjonalny książki.</p>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
<div id="podsumowanie-słowników-bing-i-affin-w-powieściach"
class="section level4">
<h4><strong>Podsumowanie słowników Bing i Affin w
powieściach</strong></h4>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>eight <span class="ot">&lt;-</span> (<span class="fu">abs</span>((eighty_days_afinn[<span class="dv">2</span>] <span class="sc">-</span> eighty_days_bing_comparison[<span class="dv">4</span>])))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>eight <span class="ot">&lt;-</span> <span class="fu">as.list</span>(eight)[[<span class="dv">1</span>]]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>moon <span class="ot">&lt;-</span> (<span class="fu">abs</span>((all_moon_afinn[<span class="dv">2</span>] <span class="sc">-</span> all_moon_bing_comparison[<span class="dv">4</span>])))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>moon <span class="ot">&lt;-</span> <span class="fu">as.list</span>(moon)[[<span class="dv">1</span>]]</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>mean_eight <span class="ot">=</span> <span class="fu">mean</span>(eight) </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>max_eight <span class="ot">=</span> <span class="fu">max</span>(eight)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>mean_moon <span class="ot">=</span> <span class="fu">mean</span>(moon) </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>max_moon <span class="ot">=</span> <span class="fu">max</span>(moon)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>max_eight_chapter <span class="ot">&lt;-</span> <span class="fu">which.max</span>(eight)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>max_moon_chapter <span class="ot">&lt;-</span> <span class="fu">which.max</span>(moon)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>same_sentiment_eight <span class="ot">&lt;-</span> (<span class="fu">sum</span>(eighty_days_afinn[<span class="dv">2</span>] <span class="sc">-</span> eighty_days_bing_comparison[<span class="dv">4</span>] <span class="sc">==</span> <span class="dv">0</span>))<span class="sc">/</span> <span class="fu">length</span>(eight) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>same_sentiment_eight_chapters <span class="ot">&lt;-</span> <span class="fu">which</span>(eighty_days_afinn[<span class="dv">2</span>] <span class="sc">-</span> eighty_days_bing_comparison[<span class="dv">4</span>] <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>same_sentiment_moon <span class="ot">&lt;-</span> (<span class="fu">sum</span>(all_moon_afinn[<span class="dv">2</span>] <span class="sc">-</span> all_moon_bing_comparison[<span class="dv">4</span>] <span class="sc">==</span> <span class="dv">0</span>))<span class="sc">/</span> <span class="fu">length</span>(moon) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>positive_negative_count_eighty <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sign</span>(eighty_days_afinn[<span class="dv">2</span>]) <span class="sc">==</span> <span class="fu">sign</span>(eighty_days_bing_comparison[<span class="dv">4</span>]) <span class="sc">*</span> <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>positive_negative_count_moon <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sign</span>(all_moon_afinn[<span class="dv">2</span>]) <span class="sc">==</span> <span class="fu">sign</span>(all_moon_bing_comparison[<span class="dv">4</span>]) <span class="sc">*</span> <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>percent_eighty <span class="ot">&lt;-</span> positive_negative_count_eighty<span class="sc">/</span><span class="fu">length</span>(eight) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>percent_moon <span class="ot">&lt;-</span> positive_negative_count_moon<span class="sc">/</span><span class="fu">length</span>(moon) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Różnica w sentymentach w &#39;W 80 dni dookoła świata&#39;: </span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Średnia:&quot;</span>, mean_eight, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Maksymalna:&quot;</span>, max_eight, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Dla rozdziału:&quot;</span>, max_eight_chapter, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Procent niezmienności:&quot;</span>, <span class="fu">sprintf</span>(<span class="st">&quot;%.3f%%&quot;</span>, same_sentiment_eight), <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Dla rozdziałów:&quot;</span>, same_sentiment_eight_chapters, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Zmiana pozytywne/negatywne:&quot;</span>, positive_negative_count_eighty, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Procentowa zmiana pozytywne/negatywne:&quot;</span>, <span class="fu">sprintf</span>(<span class="st">&quot;%.3f%%&quot;</span>, percent_eighty), <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> </span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Różnica w sentymentach w &#39;Wokół księżyca&#39;: </span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Średnia:&quot;</span>, mean_moon, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Maksymalna:&quot;</span>, max_moon, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Dla rozdziału:&quot;</span>, max_moon_chapter, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Procent niezmienności:&quot;</span>, <span class="fu">sprintf</span>(<span class="st">&quot;%.3f%%&quot;</span>, same_sentiment_moon), <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Zmiana pozytywne/negatywne:&quot;</span>, positive_negative_count_moon, <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> Procentowa zmiana pozytywne/negatywne:&quot;</span>, <span class="fu">sprintf</span>(<span class="st">&quot;%.3f%%&quot;</span>, percent_moon), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Różnica w sentymentach w &#39;W 80 dni dookoła świata&#39;: 
##  Średnia: 19.81081 
##  Maksymalna: 69 
##  Dla rozdziału: 25 
##  Procent niezmienności: 5.405% 
##  Dla rozdziałów: 7 29 
##  Zmiana pozytywne/negatywne: 7 
##  Procentowa zmiana pozytywne/negatywne: 18.919% 
##  
##  Różnica w sentymentach w &#39;Wokół księżyca&#39;: 
##  Średnia: 60.6 
##  Maksymalna: 182 
##  Dla rozdziału: 25 
##  Procent niezmienności: 0.000% 
##  Zmiana pozytywne/negatywne: 2 
##  Procentowa zmiana pozytywne/negatywne: 8.000%</code></pre>
<p>W celu dodatkowego porównania analizy wedlug słownika Bing i Afinn
zostały przedstawione powyższe statystyki. Na podstawie średniej różnicy
w sentymentach (wartość bezwględna) możemy zauważyć, że analiza dla
powieści “Wokół księżyca” jest bardziej zróżnicowana pod względem
sentymentu, a największa różnica w wartości wynosi 182 dla ostatniego
rozdziału. Jednakże należy mieć na uwadzę na podstawie poprzednich
analiz, że słownik Affin dla tej powieści ustanowił pozytywny sentyment
dla każdego rozdziału, ponadto prawie wszystkie rozdziały (poza dwoma)
ocenił na pozytywniejsze niż Bing. Średnia różnica sentymentu w “W 80
dni dookoła świata” natomiast jest dużo mniejsza, ponieważ wynosi 19.81,
przy maksymalnej różnicy 69 dla rozdziału 25, co sugeruje większą
zgodność podejść słowników, jednakże na poprzednich wykresach zauważona
została większa różnorodność - zamiana sentymentu dla konkretnych
rozdziałów.</p>
<p>Dodatkowo procent niezmienności dla pierwszej książki wskazuje 5,4%
przypadków (rozdziałów), dla których sentyment według obu słowników jest
identyczny. Dla porównania z analizy wynika, że dla drugiej książki nie
ma rozdziałów, w których sentymenty według obu słowników są identyczne,
co również można już było zaobserować na wykresach.</p>
<p>Analiza wykazuje najwięcej zmian kategorii sentymentu w rozdziałach
dla pierwszej powieści, dotyczy aż 7, co stanowi 19.9% wszystkich
rozdziałów. W przypadku drugiej książki mowa o zaledwie 2 rozdziałach,
które stanowią 8% wszystkich dla tej powieści.</p>
<p>Podsumowując, z podanych statystyk wynika, że dwa podejścia różniły
się mniej w przypadku pierwszej książki, a więcej w przypadku drugiej.
Co może oznaczać większą pewność intepretacji dla “W 80 dni dookoła
świata”. Jednak biorąc pod uwagę procentową zmianę kategorii sentymentu
oraz całą analizę, można powiedzieć, że w przypadku powieści “Wokół
księzyca” analiza i intepretacja sentymentu jest bardziej jednoznaczna
jeżeli chodzi o ‘kierunek’ - najczęstsze zmiany dotyczyły podwyższenia
sentymentu za pomocą słownika Affin, który już był pozytywny w przypadku
Bing.</p>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
</div>
</div>
<div id="słownik-nrc---rozpoznanie-emocji" class="section level2">
<h2>Słownik NRC - rozpoznanie emocji</h2>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
<p><u><strong>Słownik NRC</strong></u> (National Research Council) to
słownik, który zawiera kategorie emocji, a nie tylko wartości
sentymentalne słów. Zamiast przypisywać wartości liczbowe, słownik NRC
identyfikuje obecność lub brak pewnych emocji w tekście. Słowa są
przyporządkowane do różnych kategorii emocji, takich jak radość, smutek,
gniew, strach, zaufanie itp. Słownik NRC pozwala na bardziej szczegółową
analizę emocji obecnych w tekście, a nie tylko ogólną ocenę
sentymentu.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nrc_sentiments <span class="ot">&lt;-</span> <span class="fu">get_sentiments</span>(<span class="st">&quot;nrc&quot;</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>eighty_days_sentiments_nrc <span class="ot">=</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(eighty_days_tokens, nrc_sentiments, <span class="at">by =</span> <span class="st">&quot;word&quot;</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>all_moon_sentiments_nrc <span class="ot">=</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(all_moon_tokens, nrc_sentiments, <span class="at">by =</span> <span class="st">&quot;word&quot;</span>)</span></code></pre></div>
<ul>
<li><strong>“W 80 dnii dookoła świata” i “Wokół księżyca”</strong></li>
</ul>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>combined_sentiments_nrc <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(all_moon_sentiments_nrc, ksiażka <span class="ot">=</span> <span class="st">&quot;Wokół księżyca&quot;</span>),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(eighty_days_sentiments_nrc, ksiażka <span class="ot">=</span> <span class="st">&quot;W 80 dni dookoła świata&quot;</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>emotion_counts <span class="ot">&lt;-</span> combined_sentiments_nrc <span class="sc">%&gt;%</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ksiażka, sentiment) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(sentiment, <span class="fu">desc</span>(total))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(emotion_counts, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(sentiment, <span class="sc">-</span>total), <span class="at">y =</span> total, <span class="at">fill =</span> ksiażka)) <span class="sc">+</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">show.legend =</span> <span class="cn">TRUE</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Emocje&quot;</span>, </span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Liczba wystąpień&quot;</span>, </span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Emocje w książkach J. Verne&#39;a wg słownika NRC&quot;</span>) <span class="sc">+</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Wokół księżyca&quot;</span> <span class="ot">=</span> <span class="st">&quot;peachpuff&quot;</span>, <span class="st">&quot;W 80 dni dookoła świata&quot;</span> <span class="ot">=</span> <span class="st">&quot;steelblue&quot;</span>)) <span class="sc">+</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>))</span></code></pre></div>
<p><img src="sentyment_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Analizując wykres przedstawiający częstości występowania emocji w
książkach “W 80 dni dookoła świata” i “Wokół księżyca”, można zauważyć
interesujące podobieństwa oraz pewne różnice. Zarówno w jednej, jak i
drugiej książce dominują emocje pozytywne, co wskazuje na optymistyczny
charakter opisywanych wydarzeń. Emocje takie jak “positive”, “trust”,
“trust” i “anticipation” zajmują czołowe pozycje w obu przypadkach, co
sugeruje ogólny pozytywizm obecny w fabule.</p>
<p>Jednak warto zwrócić uwagę na różnice w występowaniu emocji
“surprise” i “anger” pomiędzy dwiema książkami. W “W 80 dni dookoła
świata” emocja “anger” zajmuje wyraźnie niższe miejsce niż “surprise”,
podczas gdy w “Wokół księżyca” jest odwrotnie. Może to wskazywać na
nieco inną dynamikę narracji oraz inne czynniki wpływające na napięcie
emocjonalne czy zaskoczenie czytelnika.</p>
<p>Podsumowując, obie książki Jules’a Verne’a charakteryzują się
dominacją pozytywnych emocji. Mimo pewnych podobieństw w rankingu
emocji, występują również subtelne różnice, które mogą wynikać z
unikalnego charakteru każdej z powieści. Ta analiza sugeruje, że obie
książki mają bardzo podobny sentyment, co wyklucza się z poprzednimi
analizami, które uznaje się za wiarygodniejsze z powodu większej
szczególowości.</p>
<p><br></p>
<div style="border-top: 1px solid black;">

</div>
<p><br></p>
</div>
<div id="podsumowanie" class="section level2">
<h2>Podsumowanie</h2>
<p>Analiza sentymentu dla powieści “W 80 dni dookoła świata” i “Wokół
księżyca” ujawnia różnice w nastrojach i emocjach obecnych w tych
książkach. Obie powieści charakteryzują się dynamiką narracji, która
przechodzi od momentów optymizmu do trudności. Wyniki analizy mogą być
zróżnicowane w zależności od zastosowanego słownika sentymentalnego.</p>
<p>“W 80 dni dookoła świata” prezentuje mieszane nastroje, począwszy od
początkowego entuzjazmu, a następnie zmagając się z różnymi wyzwaniami i
trudnościami. Pomimo tego, kończy się umiarkowanie pozytywnie, dając
czytelnikom pewne poczucie optymizmu. Może to być pozycja dla miłośników
przygód, którzy lupią napięcie i dynamikę emocji.</p>
<p>“Wokół księżyca” natomiast przeważnie emanuje pozytywnym sentymentem
przez całą powieść. Narracja jest pełna optymizmu i fascynacji podróżą
kosmiczną, co może wywoływać u czytelników uczucia inspiracji i radości.
Może to być lektura dla osób lubiących czytać o pozytwynych przygodach
bohaterów, z elementami science fiction.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
